name: flutter_ion
version: 0.1.2
description: Ion SDK for flutter.
homepage: https://github.com/pion/ion-sdk-flutter
environment:
  sdk: '>2.2.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  uuid: ^2.0.1
  events2: ^0.1.3
  sdp_transform: ^0.2.0
  flutter_webrtc: ^0.2.8
  protoo_client: ^0.3.0